name: Build Kernel for MiPad4 (clover)

on:
  workflow_call:
  workflow_dispatch:

env:
  # 1. 设备基础配置
  DEVICE_NAME : "MiPad4"
  DEVICE_CODENAME : "clover"

  # 2. 编译指令与内核源码
  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld LLVM=1 LLVM_IAS=1"

  KERNEL_SOURCE : "https://github.com/pix106/android_kernel_xiaomi_southwest-4.19.git"
  KERNEL_BRANCH : "main"

  # 3. 工具链配置 (LLVM 19.1.7)
  CLANG_SOURCE : "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz"
  CLANG_BRANCH : ""

  GCC_GNU : false
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android12L-release"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9.git"
  GCC_32_BRANCH : "android12L-release"

  # 4. 编译目标文件
  DEFCONFIG_SOURCE: ""
  DEFCONFIG_NAME : "clover_defconfig"
  DEFCONFIG_ORIGIN_IMAGE: ""
  DEFCONFIG_FROM_BOOT: false

  # 5. KernelSU 与 SUSFS 配置
  KERNELSU_SOURCE : "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/refs/heads/susfs-main/kernel/setup.sh"
  KERNELSU_BRANCH : "susfs-main"
  KERNELSU_NAME : "KernelSU"
  
  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "sukisu" # 根据您的配置需求选择
  KERNELSU_METHOD: "shell" 

  SUSFS_ENABLE : true
  SUSFS_FIXED : true

  # 6. 补丁仓库 (Patch)
  PATCHES_SOURCE: "PeterTea5822/NonGKI_Kernel_Patches"
  PATCHES_BRANCH: "main"
  SUSFS_FOLDER_FIXED: ""
  SUSFS_PATCH_FIXED: ""

  # 7. 打包配置 (AnyKernel3)
  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"
  BOOT_SOURCE : "https://github.com/boot_author/android_kernel_codename/raw/refs/heads/main/rom/source_imgs/boot.img"
  
  PACK_METHOD: "Anykernel3"
  PACK_KMODULES: "false"

  # 8. 其他功能开关
  PYTHON_VERSION: "3"
  ROM_TEXT : "lineageos_a15"
  NEED_DTBO : false
  NEED_SAFE_DTBO : false
  REKERNEL_ENABLE: "false"
  HOOK_METHOD: "syscall"
  KERNEL_PATCH: "false"
  KPM_ENABLE: "false"
  KPM_INLINE: "false"
  HIDE_STUFF: "false"
  GENERATE_DTB: "false"
  BUILD_DEBUGGER: "false"

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest
    
    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v6

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          # 如果内核有特殊的配置要求，在此处添加
          cd $GITHUB_WORKSPACE/device_kernel
          # 示例：sed -i 's/CONFIG_LOCALVERSION_AUTO=y/CONFIG_LOCALVERSION_AUTO=n/g' arch/arm64/configs/${{ env.DEFCONFIG_NAME }}

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🔧 Patch Hide Stuff
        uses: ./.github/workflows/patch-hide-stuff

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process
